spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: tp..0792
    url: jdbc:mysql://47.106.207.100:3306/blogServer
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 121.4.137.40:8848
  application:
    name: blog-basic-service
mybatis:
  mapper-locations: classpath:config/mapper/*Mapper.xml
  config-location: classpath:config/mybatis-config.xml
  type-aliases-package: com.tpblog.basic
